### ISSUE TITLE
Peer Review for 532 IA

### ISSUE THREAD

**Issue by kenuiuc** [kenuiuc/kenuiuc_van_house#1]
Render Deployment:
https://kenuiuc-van-house.onrender.com

**Comment by mozhao0331** [comment]
- the distribution plot are overlapped when I select all community. May be you can change it to facetted plots.
- for the dropdown menu, you may consider to add a select all button.
Overall, all good!

**Comment by hcwang24** [comment]
Great dashboard. I really enjoyed exploring your app about the Vancouver housing market. Here are a few constructive feedback: 
1. Make the dashboard more graphical and decorated with pictures. Adding more graphics and pictures to the dashboard can make the dashboard more attractive and engaging for users. You can consider adding images of Vancouver's cityscape, maps, or graphs that showcase the housing market's trends.
2. Remove the density on the y-axis of the density plot since it’s doesn’t really make intuitive sense. 
3. Since the communities look like a subset of the data, make indicate about this in the dashboard.

**Comment by zchen156** [comment]
Your dashboard is well-organized, and the two interactive plots complement the selection elements effectively, allowing the audience to explore land values in Vancouver based on year and legal type.

1. One suggestion I have is to add a title to your selection elements to make it easier for users to read.
2. Another suggestion is to optimize the layout of the app by placing two plots side by side to make the app look more compact, given that there are only two interactive plots.

Overall, good job!
